[package]
name = "edit-kit"
version = "0.1.0"
authors = ["Alexey Shmalko <rasen.dubi@gmail.com>"]

[dependencies]
rustbox = "*"

[lib]
name = "editkit"
path = "src/edit-kit/lib.rs"

[[bin]]
name = "ek"
